sonar.projectName=E-commerce Calidad
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=Backend
sonar.tests=Backend/tests
sonar.test.inclusions=Backend/tests/**/*.test.js

sonar.exclusions=Backend/node_modules/**,Backend/coverage/**,Backend/scripts/**
sonar.coverage.exclusions=Backend/server.js,Backend/config/**,Backend/models/**,Backend/routes/**

sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info