browser=chrome

base.url=http://127.0.0.1:5500
teknovation.url=http://127.0.0.1:5500/teknovation

implicit.wait=0
explicit.wait=3

open.pause.seconds=1
navigation.pause.seconds=0
minimum.test.seconds=1
close.pause.seconds=1